package noslabs.init;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.block.Block;
import net.minecraft.block.BlockFence;
import net.minecraft.block.BlockGlass;
import net.minecraft.block.BlockLadder;
import net.minecraft.block.BlockLever;
import net.minecraft.block.BlockNote;
import net.minecraft.block.BlockPane;
import net.minecraft.block.BlockSoulSand;
import net.minecraft.block.BlockStairs;
import net.minecraft.block.BlockTorch;
import net.minecraft.block.BlockTrapDoor;
import net.minecraft.block.material.MapColor;
import net.minecraft.block.material.Material;
import noslabs.blocks.*;
import noslabs.util.Reference;

public class ModBlocks {

	public static final List<Block> BLOCKS = new ArrayList<Block>();
	
	public static final Block AIR_VENT = new BlockMetal("airvent");
	public static final Block ASPHALT = new BlockStone("asphalt");
	public static final BlockFence ASPHALT_FENCE = new StoneFence("asphaltfence");
	public static final BlockStairs ASPHALT_STAIRS = new StoneStairs(ASPHALT.getDefaultState(), "asphaltstairs");
	public static final Block BEIGE_PLASTIC = new BlockCloth("beigeplastic");
	public static final Block BLACK_MARBLE = new BlockCloth("blackmarble");
	public static final Block BLUE_PLASTIC = new BlockCloth("blueplastic");
	public static final Block BLUE_PANELING = new BlockMetal("bluepaneling");
	public static final Block BRICK = new BlockStone("brick");
	public static final BlockFence BRICK_FENCE = new StoneFence("brickfence");
	public static final BlockStairs BRICK_STAIRS = new StoneStairs(BRICK.getDefaultState(), "brickstairs");
	public static final Block CAUTION_TAPE = new CautionTape("cautiontape");
	public static final Block CIRCUITRY = new BlockMetal("circuitry");
	public static final Block CLAY_TILE = new BlockCloth("claytile");
	public static final Block CONCRETE = new BlockStone("concrete");
	public static final BlockNote CONSOLE = new Console("console");
	public static final Block CORRUGATED_COPPER = new BlockMetal("corrugatedcopper");
	public static final Block CORRUGATED_STEEL = new BlockMetal("corrugatedsteel");
	public static final Block COUNTERTOP = new BlockWood("countertop");
	public static final BlockLadder CURTAINS = new Curtains("curtains");
	public static final Block CYAN_PLASTIC = new BlockCloth("cyanplastic");
	public static final Block DARK_STONE_BRICKS = new BlockStone("darkstonebricks");
	public static final Block DECORATIVE_CONCRETE = new BlockMetal("decorativeconcrete");
	public static final Block FANCY_TABLE = new FancyTable("fancytable");
	public static final Block FLUORESCENT_PANEL = new BlockLighting("fluorescentpanel");
	public static final BlockGlass GLASS = new Glass("glass");
	public static final BlockPane GLASS_PANE = new GlassPane("glasspane");
	public static final Block GOLD_FILGAREE = new BlockCloth("goldfilgaree");
	public static final Block GREEN_PLASTIC = new BlockCloth("greenplastic");
	public static final Block GREEN_TILES = new BlockStone("greentiles");
	public static final Block HALF_STEP = new BlockStone("halfstep");
	public static final BlockTrapDoor HATCH = new Hatch("hatch");
	public static final Block HORIZONTAL_PIPE = new BlockMetal("horizontalpipe");
	public static final Block HORIZONTAL_STRIPE = new BlockCloth("horizontalstripe");
	public static final Block IRON_PLATE = new BlockMetal("ironplate");
	public static final Block IRON_STACK = new BlockMetal("ironstack");
	public static final BlockLadder LADDER = new Ladder("ladder");
	public static final Block LAMP = new BlockLamp("lamp", false);
	public static final Block LAMP_ON = new BlockLamp("lampon", true);
	public static final BlockTorch LANTERN = new Lantern("lantern");
	public static final BlockTorch LED = new LED(false, "led");
	public static final BlockTorch LED_ON = new LED(true, "ledon");
	public static final BlockLever LEVER = new Lever("lever");
	public static final BlockLever LEVER_CLASSIC = new Lever("leverclassic");
	public static final Block LIMESTONE_BRICK = new BlockStone("limestonebrick");
	public static final Block LINOLEUM_TILE = new BlockStone("linoleumtile");
	public static final Block LIT_MONITOR = new LitMonitor("litmonitor");
	public static final Block MONITOR = new Monitor("monitor");
	public static final Block ORANGE_PLASTIC = new BlockCloth("orangeplastic");
	public static final Block PILLAR = new BlockStone("pillar");
	public static final Block PINK_STUCCO = new BlockCloth("pinkstucco");
	public static final Block PLANKS_ACACIA = new BlockWood("planksacacia");
	public static final BlockFence PLANKS_ACACIA_FENCE = new WoodFence("planksacaciafence");
	public static final BlockStairs PLANKS_ACACIA_STAIRS = new WoodStairs(PLANKS_ACACIA.getDefaultState(), "planksacaciastairs");
	public static final Block PLANKS_BIG_OAK = new BlockWood("planksbigoak");
	public static final BlockFence PLANKS_BIG_OAK_FENCE = new WoodFence("planksbigoakfence");
	public static final BlockStairs PLANKS_BIG_OAK_STAIRS = new WoodStairs(PLANKS_BIG_OAK.getDefaultState(), "planksbigoakstairs");
	public static final Block PLANKS_BIRCH = new BlockWood("planksbirch");
	public static final BlockFence PLANKS_BIRCH_FENCE = new WoodFence("planksbirchfence");
	public static final BlockStairs PLANKS_BIRCH_STAIRS = new WoodStairs(PLANKS_BIRCH.getDefaultState(), "planksbirchstairs");
	public static final Block PLANKS_JUNGLE = new BlockWood("planksjungle");
	public static final BlockFence PLANKS_JUNGLE_FENCE = new WoodFence("planksjunglefence");
	public static final BlockStairs PLANKS_JUNGLE_STAIRS = new WoodStairs(PLANKS_JUNGLE.getDefaultState(), "planksjunglestairs");
	public static final Block PLANKS_OAK = new BlockWood("planksoak");
	public static final BlockFence PLANKS_OAK_FENCE = new WoodFence("planksoakfence");
	public static final BlockStairs PLANKS_OAK_STAIRS = new WoodStairs(PLANKS_OAK.getDefaultState(), "planksoakstairs");
	public static final Block PLANKS_SPRUCE = new BlockWood("planksspruce");
	public static final BlockFence PLANKS_SPRUCE_FENCE = new WoodFence("plankssprucefence");
	public static final BlockStairs PLANKS_SPRUCE_STAIRS = new WoodStairs(PLANKS_SPRUCE.getDefaultState(), "plankssprucestairs");
	public static final Block RAW_WOOD = new BlockWood("rawwood");
	public static final Block RED_PLASTIC = new BlockCloth("redplastic");
	public static final Block REINFORCED_PANELING = new BlockMetal("reinforcedpaneling");
	public static final Block RIVETED_STEEL = new BlockMetal("rivetedsteel");
	public static final Block RUG = new BlockCloth("rug");
	public static final Block RUSTY_IRON = new BlockMetal("rustyiron");
	public static final Block SHALE = new BlockCloth("shale");
	public static final Block SINK = new BlockSink("sink", Material.IRON);
	public static final Block SMOOTH_METAL = new BlockMetal("smoothmetal");
	public static final BlockFence SMOOTH_METAL_FENCE = new MetalFence("smoothmetalfence");
	public static final BlockStairs SMOOTH_METAL_STAIRS = new WoodStairs(SMOOTH_METAL.getDefaultState(), "smoothmetalstairs");
	public static final Block STORAGE_CRATE = new BlockWood("storagecrate");
	public static final Block STRIPE_INTERSECTION = new BlockCloth("stripeintersection");
	public static final Block TABLE = new Table("table");
	public static final Block TECH_ACCENT = new BlockWood("techaccent");
	public static final Block TILE_MOSAIC = new BlockStone("tilemosaic");
	public static final Block VERTICAL_PIPE = new BlockMetal("verticalpipe");
	public static final Block VERTICAL_STRIPE = new BlockCloth("verticalstripe");
	public static final Block VIOLET_VELVET = new BlockCloth("violetvelvet");
	public static final Block WHITE_LIGHTING = new BlockLighting("whitelighting");
	public static final Block WHITE_MARBLE = new BlockStone("whitemarble");
	public static final Block WHITE_PLASTIC = new BlockCloth("whiteplastic");
	
}
